config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get '/vin_decoders/new', to: "vin_decoders#new"
  get '/vin_decoders', to: "vin_decoders#search"
  get "/vin_decoders/index", to: "vin_decoders#home"

  resources :vehicles do
    resources :maintenances, only: [:new, :create, :destroy]
  end
  
  root to: "vin_decoders#home"

end

app/models/maintenance.rb
class Maintenance < ActiveRecord::Base
	belongs_to :vehicle
	belongs_to :maintenance_type
end

app/models/maintenance_type.rb
class MaintenanceType < ActiveRecord::Base
	has_many :maintenances
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :vehicles
end

app/models/vehicle.rb
require 'httparty'

class Vehicle < ActiveRecord::Base
	belongs_to :user
	has_many :maintenances
	has_many :maintenance_types, through: :maintenances
	attr_accessor :makes
	validates :vehicle_make, :vehicle_model, :vehicle_model_year, :vehicle_trim, :vehicle_style, presence: true
end

app/models/vin_decoder.rb
require 'httparty'

class VinDecoder
	include ActiveModel::Validations

	attr_accessor :vin
	
	validates :vin, presence: true, length: {is: 17}

	def initialize(vin = nil)
		@vin = vin
	end
	
	def vin_decoder
		vehicle = HTTParty.get("https://api.edmunds.com/api/vehicle/v2/vins/#{vin}?manufactureCode=3548&fmt=json&api_key=#{ENV['edmunds_api_key']}") 
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maintenances_controller.rb
class MaintenancesController < ApplicationController

  def new
    @maint = Maintenance.new
  end

  def create
    @maint = Maintenance.new(maint_params.merge(vehicle_id: params[:vehicle_id]))
    @vehicle = Vehicle.find( params[:vehicle_id])
    if @maint.save
      redirect_to vehicle_path(@vehicle)
    end
  end

  def destroy
    @maint = Maintenance.find(params[:id])
    @maint.destroy
    @vehicle = Vehicle.find(params[:vehicle_id])
     redirect_to vehicle_path(@vehicle)
  end

  private
  def maint_params
    params.require(:maintenance).permit(:maintenance_type_id, :mileage, :shop_name, :date)
  end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :authenticate_user!

  def index
    @vehicles = Vehicle.where(user_id: current_user.id)
  end

  def show
    @vehicle = Vehicle.find( params[:id] )
  end

  def new
    @vehicle = Vehicle.new
    gon.edmunds_key = ENV['edmunds_api_key']
  end

  def create
    @vehicle = Vehicle.new(vehicle_params.merge(user_id: current_user.id))
    if @vehicle.save
      redirect_to @vehicle
    else
      render "new"
    end
  end

  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy
     redirect_to vehicles_path
  end
  
  private
  def vehicle_params
    params.require(:vehicle).permit(:vehicle_make, :vehicle_model, :vehicle_model_year, :vehicle_trim, :vehicle_style)
  end

end

app/controllers/vin_decoders_controller.rb
class VinDecodersController < ApplicationController

	def home
  end

	def new
		@vin = VinDecoder.new
	end

	def search
		@vin = VinDecoder.new(params[:vin])
		if @vin.valid?
			if @vin.vin_decoder["status"] != "NOT_FOUND"
				@vin_info = @vin.vin_decoder
			else
				render "new"
			end
		else
			render "new"
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Docarmation</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= include_gon %>
    <%= csrf_meta_tags %>
  </head>
  <body> 
    <div class="page-wrap">      
      <nav class="menu">
        <h1 id="site-name"><%= link_to "Docarmation", vin_decoders_index_path %></h1>
        <button id="hamburger-icon">&#9776</button>
         <ul class="menu-ul">
            <% if !user_signed_in? %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% else %>
              <li><%= link_to "Sign Out", destroy_user_session_path %></li>
            <% end %>
            <li><%= link_to "VIN Decoder", vin_decoders_new_path %></li>
            <li><%= link_to "Add a Vehicle", new_vehicle_path %></li>
            <li><%= link_to "My Vehicle", vehicles_path %></li>
         </ul>
      </nav>
      <h2 id="slogan">Vehicles have needs too...</h2>
      <%= yield %>
    </div>
  </body>

  <footer class="site-footer">&copy; 2014 Docarmation | <%= link_to "Home", vin_decoders_index_path %> | <a href="mailto:s.hernandez5400@gmail.com">Contact Me</a>
  </footer>
</html>

app/views/maintenances/_form.html.erb
<%= form_for(@maint, url: vehicle_maintenances_path) do |f| %>
  <% if @maint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@maint.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @maint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :maintenance_type_id, "Maintenance Type" %>
    <%= collection_select(:maintenance, :maintenance_type_id, MaintenanceType.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :mileage, "Mileage"  %>
    <%= f.text_field :mileage  %>
  </div>
  <div class="field">
    <%= f.label :shop_name, "Shop Name" %>
    <%= f.text_field :shop_name %>
  </div>
  <div class="field">
    <%= f.label :date, "Date"%>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.submit "Create Maintenance Record" %>
  </div>
<% end %>

app/views/maintenances/new.html.erb
<h2 id="maint-header">New Maintenance Record</h2>
<div class='maintenance'>
  <%= render 'form' %>
</div>
<div class="back-link">
  <button>
    <%= link_to 'Back', vehicles_path %>
  </button>
</div>

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
        <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vehicle_make, "Make" %><br />
      <% make = Edmunds::Make.new.find_new_and_used %>
      <% makes_array = make.map {|make| make['name'] } %>
      <%= f.select(:vehicle_make, options_for_select(makes_array)) %>
  </div>
  <div class="field">
    <%= f.label :vehicle_model_year, "Year" %><br />
      <% year = Edmunds::ModelYear.new.find_distinct_year_with_new_or_used %>
      <%= f.select(:vehicle_model_year, options_for_select(year)) %>
  </div>
  <div class="field">
    <%= f.label :vehicle_model, "Model" %><br>
    <%= f.select(:vehicle_model, []) %>
  </div>
  <div class="field">
    <%= f.label :vehicle_trim, "Trim"%><br>
    <%= f.select(:vehicle_trim, []) %>
  </div>
  <div class="field">
    <%= f.label :vehicle_style, "Engine"%><br>
    <%= f.select(:vehicle_style, []) %>
  </div>
  <div class="submit-field">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/index.html.erb
<ul class="list-vehicle">
  <% @vehicles.each do |vehicle| %>
  	<li> 
      <button>
        <%= link_to "#{vehicle.vehicle_model_year}" + " #{vehicle.vehicle_make}" + " #{vehicle.vehicle_model}", vehicle_path(vehicle) %>
      </button>
  	</li>
  <% end %>
</ul>

app/views/vehicles/new.html.erb
<div class="back-link">
  <button>
    <%= link_to 'Back', vehicles_path %>
  </button>
</div>
<h1>Add New Vehicle</h1>
<div class="field-container">
  <%= render 'form' %>
</div>

app/views/vehicles/show.html.erb
<div class="delete-link">
	<button>
		<%= link_to "Delete Vehicle", @vehicle, method: :delete %>
	</button>
</div>

<div class="back-link">
	<button>
		<%= link_to 'Back', vehicles_path %>
	</button>
</div>

<ul class="vehicle-show">
	<li>
		<%= @vehicle.vehicle_make %>
		<%= @vehicle.vehicle_model %>
		<%= @vehicle.vehicle_model_year %>
		<%= @vehicle.vehicle_trim %>
		<%= @vehicle.vehicle_style %>
	</li>
		<button>
			<%= link_to "Add Maintenance Record", new_vehicle_maintenance_path(@vehicle, @maint) %>
		</button>
</ul>

<div class="maint-list">
	<% @vehicle.maintenances.each do |maint| %>
		<ul>
			<li>Maintenance Category: <%= maint.maintenance_type.name %></li>
			<li>Date Performed: <%= maint.date.to_time.strftime('%B %e, %Y') %></li>
			<li>Shop: <%= maint.shop_name %></li>
			<li>Mileage: <%= maint.mileage %></li>
			<li>
				<button>
					<%= link_to "Delete Record", vehicle_maintenance_path(@vehicle, maint), method: :delete %>
				</button>
			</li>
		</ul>
	<% end %>
</div>

app/views/vin_decoders/home.html.erb
<span id="home-image"><%= image_tag("http://i.imgur.com/iA922hO.jpg") %></span>

app/views/vin_decoders/new.html.erb
<div class="vin-container">
  <% if @vin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vin.errors.count, "error") %> Prohibited this VIN from being Looked Up:</h2>

      <ul>
        <% @vin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_tag "/vin_decoders", method: :get do -%>
    
    <div class="field">
      <%= label_tag "Input 17 Character VIN" %><br>
      <%= text_field_tag :vin %>
    </div>
    <div class ="field">
      <%= submit_tag "Decode VIN" %>
    </div>
  <% end %>
</div>

app/views/vin_decoders/search.html.erb
<ul class="vin-decoded">
	<li><span>VIN:</span> <%= @vin_info['vin']%> </li>
	<li><span>Year:</span> <%= @vin_info['years'][0]['year'] %></li>
	<li><span>Make:</span> <%= @vin_info['make']['name'] %></li>
	<li><span>Model:</span> <%= @vin_info['model']['name'] %></li>
	<li><span>Vehicle Style:</span> <%= @vin_info['categories']['vehicleStyle'] %> </li>
	<li><span>Body Type:</span> <%= @vin_info['categories']['primaryBodyType'] %></li>
	<li><span>EPA Class:</span> <%= @vin_info['categories']['EPAClass'] %></li>
	<li><span>Driven Wheels:</span> <%= @vin_info['drivenWheels'] %></li>
	<li><span>Number Of Doors:</span> <%= @vin_info['numOfDoors'] %></li>
	<li><span>True Market Value:</span> $<%= @vin_info['price']['usedTmvRetail']%></li>
	<li><span>Used Private Party Value:</span> $<%= @vin_info['price']['usedPrivateParty'] %> </li>
	<li><span>Used Trade-In Value:</span> $<%= @vin_info['price']['usedTradeIn'] %> </li>
	<button><%= link_to "Decode another VIN", vin_decoders_new_path %></button>
</ul>